"""
scripts/validate_no_internal_leaks.py
CI/CD Guard Universal: Valida que la documentacion y el codigo fuente no contengan
acronimos internos (GP-xxx), marcas de andamiaje o divulgaciones de datos sinteticos.
"""

from pathlib import Path
import re
import sys

PROHIBITED_LEAK_PATTERNS = [
    (r"GP-\d{3,6}", "Internal Ghost Project ID (GP-xxx)"),
    (r"Ghost\s+Architect", "Internal system moniker ('Ghost Architect')"),
    (r"anti_monotony_memory", "Internal module reference ('anti_monotony_memory')"),
    (r"synthetic\s+dataset", "Synthetic data disclosure ('synthetic dataset')"),
    (r"dummy\s+data", "Dummy data disclosure ('dummy data')"),
    (r"generated\s+by\s+(?:ai|gpt|claude|gemini|antigravity)", "AI provenance disclosure ('generated by...')"),
]

EXCLUDED_DIRS = {".git", ".pytest_cache", "__pycache__", ".venv", "venv", "build", "dist"}
INCLUDED_EXTS = {".py", ".sql", ".sh", ".bat", ".md", ".toml", ".ini"}
EXCLUDED_FILES = {"scaffolding.manifest.json", "validate_no_internal_leaks.py"}

def main():
    root = Path(__file__).resolve().parent.parent
    violations = []

    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(excluded in path.parts for excluded in EXCLUDED_DIRS):
            continue
        if path.name in EXCLUDED_FILES:
            continue
        if path.suffix not in INCLUDED_EXTS and path.name != "Dockerfile":
            continue

        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        lines = content.splitlines()
        for pattern_str, label in PROHIBITED_LEAK_PATTERNS:
            regex = re.compile(pattern_str, re.IGNORECASE)
            for idx, line in enumerate(lines, 1):
                match = regex.search(line)
                if match:
                    rel_path = path.relative_to(root)
                    violations.append(
                        f"[{rel_path}:{idx}] {label} matched '{match.group(0)}': {line.strip()[:80]}"
                    )

    if violations:
        print(f"[Leaks Guard FAIL] Se detectaron {len(violations)} fugas internas prohibidas:")
        for v in violations:
            print(f"  - {v}")
        sys.exit(1)

    print("[Leaks Guard PASS] Zero fugas internas detectadas en el repositorio.")
    sys.exit(0)


if __name__ == "__main__":
    main()